- name: apt upgrade
  apt: upgrade=dist update_cache=yes

- name: install basic system packages
  apt: name={{item}} state=present
  with_items:
  - htop
  - vim
  - git
  - unzip
  - python3
  - python3-pip
  - python
  - python-dev
  - python-pip

- name: change root password
  user: name=root password=$6$n8I8WiGqmbCU$ElHrLqhi9SWLLBT27UWsP0xwXQ0cz.QRsk9vq.uC0y7zPXpiCzHtfcVEPlFhOFGh5wKRGhiygwyTk5qbf4YI21

- name: clone repo
  git: repo=https://github.com/brmson/Personal-Assistant.git dest=/root/Personal-Assistant version=master force=yes depth=5

- name: create config folder
  file:
    path: /root/config/
    state: directory
