- name: install pocketSphinx
  include: pocketSphinx.yml
  when: attention_word == 'pocketSphinx'
  tags:
  - attention_word
  - pocketSphinx

- name: install pocketSphinx with Alsa
  include: pocketSphinxAlsa.yml
  when: attention_word == 'pocketSphinxAlsa'
  tags:
  - attention_word
  - pocketSphinx_alsa

- name: copy config
  copy:
    src: "{{ attention_word }}.yml"
    dest: /root/config/attention_word.yml
    force: yes
  tags:
  - attention_word
