# Default configuration file
#
# All paths are absolute or relative to this file

# global config
global:
  minPort: 5000
  maxPort: 5999
  maxRetries: 99
  logPath: ../logs/

# attention word module config
attword:
  path: ../modules/attentionWord/pocketSphinx/attentionWord.py
  attentionWord: phoenix
  threshold: 1
  modelPath: /usr/local/share/pocketsphinx/model/en-us/en-us
  dictionaryPath: /usr/local/share/pocketsphinx/model/en-us/en-us/dictionary.dict

# speech-to-text module config
speechToText:
  path: ../modules/speechToText/pocketSphinx/speechToText.py
  modelPath: /usr/local/share/pocketsphinx/model/en-us/en-us
  dictionaryPath: /usr/local/share/pocketsphinx/model/en-us/en-us/dictionary.dict
  grammarPath: /usr/local/share/pocketsphinx/model/en-us/en-us/grammar.lm

# get intent module config
getIntent:
  path: ../modules/getIntent/getIntent.py
# dbToken: NUFTF6VJH6EC3BN5S2EK2STCPYGKPPNR
# Jakub Konrad Database
  dbToken: 3LH5Q3E3KEIYYVINQKBLOL2QGAIQ2IRG
# Jakub Drapela Database

# query module config
queryProcessor:
  path: ../modules/querylogic/query_control.py
  country: Czech Republic
  city: Prague

# text-to-speech module config
textToSpeech:
  path: ../modules/textToSpeech/mimicModule/TextToSpeachModule.py
  voice: rms
