# Default configuration file
#
# All paths are absolute or relative to this file

# global config
global:
  minPort: 5000
  maxPort: 5999
  maxRetries: 99

# attention word module config
attword:
  path: ../modules/attentionWord/pocketSphinx/attentionWord.py
  attentionWord: phoenix
  threshold: 1
  modelPath: /usr/local/share/pocketsphinx/model/en-us/en-us
  dictionaryPath: /usr/local/share/pocketsphinx/model/en-us/en-us/dictionary.dict

# speech-to-text module config
speechToText:
  path: ../modules/speechToText/speechToText.py
  dbToken: NUFTF6VJH6EC3BN5S2EK2STCPYGKPPNR

# get intent module config
getIntent:
  path: ../modules/getIntent/getIntent.py
  dbToken: NUFTF6VJH6EC3BN5S2EK2STCPYGKPPNR

# query module config
queryProcessor:
  path: ../modules/querylogic/query_control.py
  country: Czech Republic
  city: Prague

# text-to-speech module config
textToSpeech:
  path: ../modules/textToSpeech/mimicModule/TextToSpeachModule.py
  voice: rms
