- name: install pocketSphinx
  include: pocketSphinx.yml
  when: speech_to_text == 'pocketSphinx'
  tags:
  - speech_to_text
  - pocketSphinx

- name: install SpeachReco
  include: SpeachReco.yml
  when: speech_to_text == 'SpeachReco'
  tags:
  - speech_to_text
  - SpeachReco

- name: copy config
  copy:
    src: "{{ speech_to_text }}.yml"
    dest: /root/config/speech_to_text.yml
    force: yes
  tags:
  - speech_to_text
