- name: install (via pip3) required python libraries for kernel
  pip: requirements=/root/Personal-Assistant/kernel/requirements.txt executable=pip3

- name: copy config
  copy:
    src: config.yml
    dest: /root/config/global.yml
    force: yes

- name: copy run scripts
  copy:
    dest: /root/{{ item }}
    src: "{{ item }}"
    mode: 755
    force: yes
  with_items:
    - run.py
    - web.py
